	\context ChordNames 
		\chords { 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		b2:m b2:m/g 
		\set majorSevenSymbol = \markup { "maj7" } d1:maj7
		g1
		d1:/fis
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		b2:m b2:m/g 
		\set majorSevenSymbol = \markup { "maj7" } d1:maj7
		g1
		d1:/fis
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		b2:m b2:m/g 
		\set majorSevenSymbol = \markup { "maj7" } d1:maj7
		g1
		d1:/fis
		f1
		s1
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		a2 \set majorSevenSymbol = \markup { "maj7" } a2:maj7 
		}
