\context ChordNames \chords {
	\set majorSevenSymbol = \markup { "maj7" }
	\set chordChanges = ##t

	% Intro
	a2 a2:maj7
	a2 a2:maj7

	% Cordero de Dios... ten piedad...
	a2 a2:maj7
	b2:m b2:m/g
	d1:maj7
	g1
	d1:/fis
	a2 a2:maj7
	a2 a2:maj7

	% Cordero de Dios... ten piedad...
	a2 a2:maj7
	b2:m b2:m/g
	d1:maj7
	g1
	d1:/fis
	a2 a2:maj7
	a2 a2:maj7

	% Cordero de Dios... danos la paz...
	a2 a2:maj7
	b2:m b2:m/g
	d1:maj7
	g1
	d1:/fis
	f1
	s1

	% Outro
	a2 a2:maj7
	a2 a2:maj7
	a2 a2:maj7
}
